Push zipkin image.

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -57,7 +57,7 @@ jobs:
       steps:
         - name: Checkout Code
           uses: actions/checkout@v4
-  
+
         - name: Set up JDK 17
           uses: actions/setup-java@v4
           with:
@@ -216,7 +216,21 @@ jobs:
             docker tag ${{ secrets.DOCKERHUB_USERNAME }}/$image ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/$(echo ${image%%:*} | tr '[:upper:]' '[:lower:]'):${image##*:}
             docker push ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/${image%%:*}:${image##*:}
           done
-
+        
+        
+           # Use official Zipkin Docker images
+          # Define the image name
+          IMAGE_NAME="${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/zipkin:latest"
+          
+          if ! aws ecr describe-images --repository-name zipkin --image-ids imageTag=latest >/dev/null 2>&1; then
+          echo "Image not found in ECR. Pushing the image..."
+          docker tag openzipkin/zipkin:latest  ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/zipkin:latest
+          docker push ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/zipkin:latest
+          else
+          echo "Zipkin already exists in ECR. No need to push."
+          fi
+         
+         
 
 # Old deployment steps
 #  deploy:
@@ -267,6 +281,7 @@ jobs:
               --service "$service" \
               --force-new-deployment
           done
+
       - name: Confirm ECS deployment status
         run: |
           services=("api-gateway-service" "delivery-service" "user-service" "order-service" "restaurant-service" "notification")
